### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Twillster** [Ley21/ffxiv_minions#10]
Sorting on the FC pages is not working in certain areas; it seems to work sometimes for certain orders but not in reverse; some members in our FC (9237023573225247631) won't sync so not sure if this causes an issue (using Chrome)

- Minions
- Mounts
- All

I typically would want to look at all members when sorting things; so as a side note it would be nice if either by cookie or URL params, it could remember how many per page I was looking at. Also, might be helpful to have "Who doesn't have X" instead of just "Who has X" (whilst not hard to work out, I usually want to check who needs a spare item I have).

Thanks for the site though :)

**Comment by Ley21** [comment]
Sry for late response.
I will take a look on this problem. The feature 'who has not?' is a nice idea I will take a look how I could implement it.
The sorting is also I issue I found but I dont has a solution yet.
