### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by symemys** [Ley21/ffxiv_minions#9]
Hello,
(i am french, sorry for my bad english)
(and i don't know GitHub, sorry if it's not here to post...)

I love FFXIV Collector!
But i saw some errors on my character, "Symemys Asura" on Moogle.

"Witch's Broom" is count in Missing Mount, but i have it.
"Mummy's Little Mummy" is count in Missing Minions, but i have it
"Dress-up Y'shtola" is count in Missing Minions, but i have it
"Wind-up Y'shtola" is count in Missing Minions, but i have it

Anyway, thank you for your great work!

**Comment by Ley21** [comment]
Fix your issue and do a force update for your minions.

p.s. Cute Lala ^^
